def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('login', '/login')
    config.add_route('logout', '/logout')
    config.add_route('manage', '/manage/{id:\w+}')
    config.add_route('register', '/register')
    config.add_route('categories', '/categories')
    config.add_route('attributes', '/attributes')
    config.add_route('display', '/display')
    config.add_route('test_img', 'test/{id:\d+}')
